[package]
name = "meilisearch-http"
description = "MeiliSearch HTTP server"
version = "0.14.0"
license = "MIT"
authors = [
    "Quentin de Quelen <quentin@dequelen.me>",
    "Clément Renault <clement@meilisearch.com>",
]
edition = "2018"

[[bin]]
name = "meilisearch"
path = "src/main.rs"

[features]
default = ["sentry"]

[dependencies]
actix-cors = "0.2.0"
actix-http = "1"
actix-rt = "1"
actix-service = "1.0.5"
actix-web = { version = "2.0.0", features = ["rustls"] }
actix-web-macros = "0.1.0"
anyhow = "1.0"
async-raft = "0.5.0"
bincode = "1.3.1"
bytes = "0.5.4"
chrono = { version = "0.4.11", features = ["serde"] }
crossbeam-channel = "0.4.2"
env_logger = "0.7.1"
flate2 = "1.0.16"
futures = "0.3.4"
heed = "0.8.0"
http = "0.1.19"
indexmap = { version = "1.3.2", features = ["serde-1"] }
log = "0.4.8"
main_error = "0.1.0"
meilisearch-core = { path = "../meilisearch-core", version = "0.14.0" }
meilisearch-error = { path = "../meilisearch-error", version = "0.14.0" }
meilisearch-schema = { path = "../meilisearch-schema", version = "0.14.0" }
meilisearch-tokenizer = {path = "../meilisearch-tokenizer", version = "0.14.0"}
mime = "0.3.16"
rand = "0.7.3"
regex = "1.3.6"
rustls = "0.16.0"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = { version = "1.0.50", features = ["preserve_order"] }
serde_qs = "0.5.2"
sha2 = "0.8.1"
siphasher = "0.3.2"
slice-group-by = "0.2.6"
structopt = "0.3.12"
tar = "0.4.29"
tempfile = "3.1.0"
tokio = { version = "0.2.18", features = ["macros"] }
tonic = "0.3.0"
ureq = { version = "0.12.0", features = ["tls"], default-features = false }
walkdir = "2.3.1"
whoami = "0.8.1"

[dependencies.sentry]
version = "0.18.1"
default-features = false
features = [
    "with_client_implementation",
    "with_panic",
    "with_failure",
    "with_device_info",
    "with_rust_info",
    "with_reqwest_transport",
    "with_rustls",
    "with_env_logger"
]
optional = true

[dev-dependencies]
serde_url_params = "0.2.0"
tempdir = "0.3.7"
tokio = { version = "0.2.18", features = ["macros", "time"] }
tonic-build = "0.3.0"

[dev-dependencies.assert-json-diff]
git = "https://github.com/qdequele/assert-json-diff"
branch = "master"

[build-dependencies]
vergen = "3.1.0"

[target.'cfg(unix)'.dependencies]
jemallocator = "0.3.2"
